version: '3'
networks:
  app-tier:
    driver: bridge

services:
  backend:
    build: ./backend/
    image: bigworldgraph_backend
    ports:
      - "6050:5000"
    depends_on:
      - neo4j
    environment:
      - ENV=demo
      - PYTHONPATH=/data/src/app/
      - PYWIKIBOT2_DIR=/data/src/app/bwg/user-config.py
      - PYWIKIBOT2_NO_USER_CONFIG=1
      - API_CONFIG_PATH=/data/src/app/bwg/api/api_config.py
      - NEO4J_PORT=7687
      - API_HOST=0.0.0.0
      - NEO4J_HOST=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - LOAD_DEMO_DATA=1
      - DEMO_RELATIONS_PATH=/demo_pipeline/demo_relations.json
      - DEMO_PROPERTIES_PATH=/demo_pipeline/demo_properties.json
    networks:
      - app-tier
    volumes:
      - ./backend/data/pipeline_demo/:/demo_pipeline
  neo4j:
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
    image: neo4j:3.0
    ports:
      - "6060:7474"
      - "6070:7687"
    networks:
      - app-tier
  frontend:
    build: ./frontend/
    image: bigworldgraph_frontend
    ports:
        - "8080:8080"
    networks:
        - app-tier
    volumes:
        - ./frontend:/frontend
        - /frontend/node_modules
