version: '3'

services:
  frontend:
    image: majdigital/${COMPOSE_PROJECT_NAME}_frontend
    container_name: ${COMPOSE_PROJECT_NAME}_frontend
    build: ./frontend/
    command: sh -c 'npm run build && npm run serve'
    ports:
      - "3000:3000"